// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwfIaBqu_vNvhM2plRkikdfMBivOM9Cc',
    appId: '1:643018062199:android:7d67b3cf0bc55ab2f24972',
    messagingSenderId: '643018062199',
    projectId: 'liveapp-66979',
    storageBucket: 'liveapp-66979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FBK3BshdNUbXWwxkl_hzeYWl2o8Kg_I',
    appId: '1:643018062199:ios:8a0a3e2a720a4c2ff24972',
    messagingSenderId: '643018062199',
    projectId: 'liveapp-66979',
    storageBucket: 'liveapp-66979.firebasestorage.app',
    iosBundleId: 'com.example.liveapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_DzAe52y8ao0gmSyx7FhmQrAoR6l92c8',
    appId: '1:643018062199:web:a8052e5262684da8f24972',
    messagingSenderId: '643018062199',
    projectId: 'liveapp-66979',
    authDomain: 'liveapp-66979.firebaseapp.com',
    storageBucket: 'liveapp-66979.firebasestorage.app',
    measurementId: 'G-ZZ0K4Y77J0',
  );
}
